/*
  Darja Drill — vocab bank
  ------------------------------------------------------------
  One entry per item:  [darja, english, arabic, alt, flags]
    darja   Arabizi exactly as the slides write it
    english the meaning; " — " or " · " separates accepted alternatives,
            "— to a man / to a woman" marks who you're speaking to
    arabic  vowel-marked Arabic script for the voice ("" = no audio)
            Always keep the shadda (ّ) on doubled letters.
    alt     other forms heard (shown as "also heard")
    flags   "x" = not from the slides (Claude's addition)
            "u" = Arabic spelling unsure — check with the teacher

  To add a new week: copy a topic block, give it a new id, set week to the
  next number, and paste the new items in. Nothing else needs to change.
*/
window.VOCAB = {
updated: '2026-10-04',
topics: [
{id:'questions', name:'Questions', week:1, deck:'Deck 1', items:[
  ['Wech rak?', 'How are you? — to a man', 'وَاشْ رَاكْ؟', 'Ki rak? · Labas?'],
  ['Wech raki?', 'How are you? — to a woman', 'وَاشْ رَاكِي؟', 'Ki raki? · Labas?'],
  ['W nta?', 'And you? — to a man', 'وَنْتَا؟'],
  ['W nti?', 'And you? — to a woman', 'وَنْتِي؟'],
  ['Wech asmek? · Wesmek?', "What's your name?", 'وَاشْ اسْمَكْ؟', 'Ki ysemmouk?'],
  ['Men win nta?', 'Where are you from? — to a man', 'مِنْ وِينْ نْتَا؟', 'Mnin nta?'],
  ['Men win nti?', 'Where are you from? — to a woman', 'مِنْ وِينْ نْتِي؟', 'Mnin nti?'],
  ['Ana men [place]', 'I am from [place]', 'أَنَا مِنْ'],
  ['Ch7al fi 3omrek?', 'How old are you?', 'شْحَالْ فِي عُمْرَكْ؟'],
  ['3andi [n] sna · Fi 3omri [n]', 'I am [n] years old', 'فِي عُمْرِي'],
  ['Win teskoun?', 'Where do you live? — to a man', 'وِينْ تَسْكُنْ؟'],
  ['Win teskni?', 'Where do you live? — to a woman', 'وِينْ تَسْكْنِي؟'],
  ['Ana neskoun fi [place]', 'I live in [place]', 'أَنَا نَسْكُنْ فِي'],
  ['Wech tekhdem?', 'What do you do for work? — to a man', 'وَاشْ تَخْدَمْ؟'],
  ['Wech tekhdemi?', 'What do you do for work? — to a woman', 'وَاشْ تَخْدْمِي؟'],
  ['Ana nakhdem fi [field]', 'I work in [field]', 'أَنَا نَخْدَمْ فِي'],
  ['Wach t7eb dir?', 'What do you like to do? — to a man', 'وَاشْ تْحَبّْ دِيرْ؟'],
  ['Wach t7ebbi diri?', 'What do you like to do? — to a woman', 'وَاشْ تْحَبِّي دِيرِي؟']
]},
{id:'endings', name:'Endings & verbs', week:1, deck:'Deck 1', items:[
  ['asmi', 'my name', 'اسْمِي'],
  ['asmek', 'your name', 'اسْمَكْ'],
  ['asmou', 'his name', 'اسْمُو'],
  ['asmha · assemha', 'her name', 'اسْمْهَا'],
  ['3omri', 'my age', 'عُمْرِي'],
  ['3omrek', 'your age', 'عُمْرَكْ'],
  ['3omrou', 'his age', 'عُمْرُو'],
  ['3omrha · 3morha', 'her age', 'عُمْرْهَا'],
  ['neskoun', 'I live', 'نَسْكُنْ'],
  ['teskoun', 'you (m) live · she lives', 'تَسْكُنْ'],
  ['teskni', 'you (f) live', 'تَسْكْنِي'],
  ['yeskoun', 'he lives', 'يَسْكُنْ'],
  ['nakhdem', 'I work', 'نَخْدَمْ'],
  ['tekhdem', 'you (m) work · she works', 'تَخْدَمْ'],
  ['tekhdemi', 'you (f) work', 'تَخْدْمِي'],
  ['yekhdem', 'he works', 'يَخْدَمْ'],
  ['n7eb', 'I like', 'نْحَبّْ'],
  ['t7eb', 'you (m) like · she likes', 'تْحَبّْ'],
  ['t7ebbi', 'you (f) like', 'تْحَبِّي'],
  ['y7eb', 'he likes', 'يْحَبّْ']
]},
{id:'stems', name:'Him & her', week:1, deck:'Deck 1', items:[
  ['Fi 3omrou [n]', 'He is [n] years old', 'فِي عُمْرُو'],
  ['Fi 3morha [n]', 'She is [n] years old', 'فِي عُمْرْهَا'],
  ['Yeskoun fi [place]', 'He lives in [place]', 'يَسْكُنْ فِي'],
  ['Teskoun fi [place]', 'She lives in [place]', 'تَسْكُنْ فِي'],
  ['Yekhdem fi [place]', 'He works in [place]', 'يَخْدَمْ فِي'],
  ['Tekhdem fi [place]', 'She works in [place]', 'تَخْدَمْ فِي'],
  ['N7eb ndir [activity]', 'I like doing [activity]', 'نْحَبّْ نْدِيرْ'],
  ['Houwa men [place]', 'He is from [place]', 'هُوَّ مِنْ', '', 'x'],
  ['Hiya men [place]', 'She is from [place]', 'هِيَّ مِنْ', '', 'x'],
  ['Men win houwa?', 'Where is he from?', 'مِنْ وِينْ هُوَّ؟', '', 'x'],
  ['Men win hiya?', 'Where is she from?', 'مِنْ وِينْ هِيَّ؟', '', 'x']
]},
{id:'family', name:'Family', week:1, deck:'Deck 1', items:[
  ['Baba · Bouya', 'my father', 'بَابَا'],
  ['Yemma · Mama', 'my mother', 'يَمَّا'],
  ['Khouya', 'my brother', 'خُويَا'],
  ['Khti', 'my sister', 'خْتِي'],
  ['Weldi · Wlidi · Bni', 'my son', 'وَلْدِي'],
  ['Benti', 'my daughter', 'بَنْتِي'],
  ['Jedi', 'my grandfather', 'جَدِّي'],
  ['Jedati · Mani · Mima · 7ana', 'my grandmother', 'جَدَّتِي'],
  ['3emi', 'my paternal uncle — father’s brother', 'عَمِّي'],
  ['3emti', 'my paternal aunt — father’s sister', 'عَمّْتِي'],
  ['Khali', 'my maternal uncle — mother’s brother', 'خَالِي'],
  ['Khalti', 'my maternal aunt — mother’s sister', 'خَالْتِي'],
  ['Weld 3emi', 'my cousin, son of my father’s brother', 'وَلْدْ عَمِّي'],
  ['Weld 3emti', 'my cousin, son of my father’s sister', 'وَلْدْ عَمّْتِي'],
  ['Weld khali', 'my cousin, son of my mother’s brother', 'وَلْدْ خَالِي'],
  ['Weld khalti', 'my cousin, son of my mother’s sister', 'وَلْدْ خَالْتِي'],
  ['Bent 3emi', 'my cousin, daughter of my father’s brother', 'بَنْتْ عَمِّي'],
  ['Bent 3emti', 'my cousin, daughter of my father’s sister', 'بَنْتْ عَمّْتِي'],
  ['Bent khali', 'my cousin, daughter of my mother’s brother', 'بَنْتْ خَالِي'],
  ['Bent khalti', 'my cousin, daughter of my mother’s sister', 'بَنْتْ خَالْتِي'],
  ['Weld khouya', 'my nephew — my brother’s son', 'وَلْدْ خُويَا'],
  ['Weld khti', 'my nephew — my sister’s son', 'وَلْدْ خْتِي'],
  ['Bent khouya', 'my niece — my brother’s daughter', 'بَنْتْ خُويَا'],
  ['Bent khti', 'my niece — my sister’s daughter', 'بَنْتْ خْتِي']
]},
{id:'phrases', name:'Phrases', week:1, deck:'Deck 1', items:[
  ['Ana dziri', 'I am Algerian — a man', 'أَنَا دْزِيرِي'],
  ['Ana dziriya', 'I am Algerian — a woman', 'أَنَا دْزِيرِيَّة'],
  ['Ana wahrani', 'I am from Oran — a man', 'أَنَا وَهْرَانِي'],
  ['Ana wahraniya', 'I am from Oran — a woman', 'أَنَا وَهْرَانِيَّة'],
  ['Labas', 'fine', 'لَابَاسْ'],
  ['Ghaya', 'great', 'غَايَة'],
  ['Hamdoulleh', 'thank God', 'الْحَمْدُ لِلَّه']
]},
{id:'calendar', name:'Calendar', week:3, deck:'Deck 3', items:[
  ['L7ad', 'Sunday', 'لْحَدْ'],
  ['Tnin', 'Monday', 'لَتْنِينْ'],
  ['Tleta', 'Tuesday', 'تْلَاتَة'],
  ['Lareb3a', 'Wednesday', 'لَارْبْعَة'],
  ['Lkhmis', 'Thursday', 'لَخْمِيسْ'],
  ['Djem3a', 'Friday', 'الْجَمْعَة'],
  ['Sebt', 'Saturday', 'السَّبْتْ'],
  ['Lbare7', 'yesterday', 'الْبَارَحْ'],
  ['Ghedwa', 'tomorrow', 'غُدْوَة'],
  ['Loul bara7', 'the day before yesterday', 'لُولْ الْبَارَحْ'],
  ['Ghir ghedwa', 'the day after tomorrow', 'غِيرْ غُدْوَة'],
  ['Youm', 'day', 'يُومْ'],
  ['Nhar', 'daytime — a calendar day', 'نْهَارْ'],
  ['Smana', 'week', 'سْمَانَة'],
  ['Chhar', 'month', 'شْهَرْ'],
  ['3am', 'year', 'عَامْ'],
  ['Fousoul', 'the seasons', 'الْفُصُولْ'],
  ['Rbi3', 'spring', 'الرّْبِيعْ'],
  ['Sif', 'summer', 'الصِّيفْ'],
  ['Khrif', 'autumn', 'الْخْرِيفْ'],
  ['Chta', 'winter', 'الشّْتَا'],
  ['Janvi · Janvier', 'January', 'جَانْفِي'],
  ['Fervryi · Février', 'February', 'فِيفْرِي'],
  ['Mars', 'March', 'مَارْسْ'],
  ['Avril', 'April', 'أَفْرِيلْ'],
  ['Mai', 'May', 'مَايْ'],
  ['Juin', 'June', 'جْوَانْ'],
  ['Juillet', 'July', 'جْوِيلِيَّة'],
  ['Aout', 'August', 'أُوتْ'],
  ['Septembre', 'September', 'سَبْتَمْبَرْ'],
  ['Octobre', 'October', 'أُكْتُوبَرْ'],
  ['Novembre', 'November', 'نُوفَمْبَرْ'],
  ['Decembre', 'December', 'دِيسَمْبَرْ'],
  ['Smana ljaya', 'next week', 'السّْمَانَة الْجَايَّة'],
  ['Smana li fatat', 'last week', 'السّْمَانَة اللِّي فَاتَتْ'],
  ['Chhar ljay', 'next month', 'الشّْهَرْ الْجَايْ'],
  ['Chhar li fat', 'last month', 'الشّْهَرْ اللِّي فَاتْ'],
  ['L3am ljay', 'next year', 'الْعَامْ الْجَايْ'],
  ['L3am li fat', 'last year', 'الْعَامْ اللِّي فَاتْ']
]},
{id:'numbers', name:'Numbers', week:4, deck:'Numbers 1–2', items:[
  ['Sifr', '0', 'صِفْرْ'],
  ['Wa7ad', '1', 'وَاحَدْ'],
  ['Zouj · Tnin', '2', 'زُوجْ'],
  ['Tletta', '3', 'تْلَاتَة'],
  ['Rab3a', '4', 'رَبْعَة'],
  ['Khemsa', '5', 'خَمْسَة'],
  ['Setta', '6', 'سِتَّة'],
  ['Sab3a', '7', 'سَبْعَة'],
  ['Tménya', '8', 'تْمَنْيَة'],
  ['Tas3a', '9', 'تَسْعَة'],
  ['3achra', '10', 'عَشْرَة'],
  ['7dash', '11', 'حْدَاشْ'],
  ['Tnash', '12', 'طْنَاشْ'],
  ['Tlettash', '13', 'تْلَطَّاشْ'],
  ['Rbe3ttash', '14', 'رْبَعْطَاشْ'],
  ['Khmsttash', '15', 'خْمَسْطَاشْ'],
  ['Settash', '16', 'سَطَّاشْ'],
  ['Sba3ttash', '17', 'سْبَعْطَاشْ'],
  ['Tmenttash', '18', 'تْمَنْطَاشْ'],
  ['Tse3ttash', '19', 'تْسَعْطَاشْ'],
  ['3achrin', '20', 'عَشْرِينْ'],
  ['Tlatin', '30', 'تْلَاتِينْ'],
  ['Rab3in', '40', 'رَبْعِينْ'],
  ['Khamsin', '50', 'خَمْسِينْ'],
  ['Settin', '60', 'سِتِّينْ'],
  ['Sab3in', '70', 'سَبْعِينْ'],
  ['Tmanin', '80', 'تْمَانِينْ'],
  ['Tas3in', '90', 'تَسْعِينْ'],
  ['Mia', '100', 'مْيَة'],
  ['Mitin', '200', 'مْيَتِينْ'],
  ['Teltmia', '300', 'تَلْتْمْيَة', '', 'u'],
  ['Reb3mia', '400', 'رَبْعْمْيَة', '', 'u'],
  ['Khemsmia', '500', 'خَمْسْمْيَة', '', 'u'],
  ['Settmia', '600', 'سَتّْمْيَة', '', 'u'],
  ['Seb3mia', '700', 'سَبْعْمْيَة', '', 'u'],
  ['Temnemia', '800', 'تْمَنْمْيَة', '', 'u'],
  ['Tes3mia', '900', 'تَسْعْمْيَة', '', 'u'],
  ['Alf', '1,000', 'أَلْفْ'],
  ['Alfyn', '2,000', 'أَلْفِينْ'],
  ['Teltalaf', '3,000', 'تَلْتْ الَافْ'],
  ['Reb3alaf', '4,000', 'رَبْعْ الَافْ'],
  ['Khmsalaf', '5,000', 'خَمْسْ الَافْ'],
  ['Settalaf', '6,000', 'سَتّْ الَافْ'],
  ['Seb3alaf', '7,000', 'سَبْعْ الَافْ'],
  ['Temnalaf', '8,000', 'تْمَنْ الَافْ'],
  ['Tes3alaf', '9,000', 'تَسْعْ الَافْ'],
  ['3chralaf', '10,000', 'عَشْرْ الَافْ'],
  ['7dach nalef', '11,000', 'حْدَاشْ نَالَفْ'],
  ['Tnach nalef', '12,000', 'طْنَاشْ نَالَفْ'],
  ['Tletach nalef', '13,000', 'تْلَطَّاشْ نَالَفْ'],
  ['Reb3tach nalef', '14,000', 'رْبَعْطَاشْ نَالَفْ'],
  ['Khmstach nalef', '15,000', 'خْمَسْطَاشْ نَالَفْ'],
  ['Settach nalef', '16,000', 'سَطَّاشْ نَالَفْ'],
  ['Sb3tach nalef', '17,000', 'سْبَعْطَاشْ نَالَفْ'],
  ['Tementach nalef', '18,000', 'تْمَنْطَاشْ نَالَفْ'],
  ['Ts3tach nalef', '19,000', 'تْسَعْطَاشْ نَالَفْ'],
  ['3echrin alef', '20,000', 'عَشْرِينْ أَلَفْ'],
  ['Tletin alef', '30,000', 'تْلَاتِينْ أَلَفْ'],
  ['Rb3in alef', '40,000', 'رَبْعِينْ أَلَفْ'],
  ['Khamsin alef', '50,000', 'خَمْسِينْ أَلَفْ'],
  ['Settin alef', '60,000', 'سِتِّينْ أَلَفْ'],
  ['Sb3in alef', '70,000', 'سَبْعِينْ أَلَفْ'],
  ['Tmanin alef', '80,000', 'تْمَانِينْ أَلَفْ'],
  ['Ts3in alef', '90,000', 'تَسْعِينْ أَلَفْ'],
  ['Mia talef', '100,000', 'مْيَة تَالَفْ'],
  ['Mitin alef', '200,000', 'مْيَتِينْ أَلَفْ'],
  ['Tletemia talef', '300,000', 'تَلْتْمْيَة تَالَفْ', '', 'u'],
  ['Reb3emia talef', '400,000', 'رَبْعْمْيَة تَالَفْ', '', 'u'],
  ['Khmsmia talef', '500,000', 'خَمْسْمْيَة تَالَفْ', '', 'u'],
  ['Settmia talef', '600,000', 'سَتّْمْيَة تَالَفْ', '', 'u'],
  ['Sb3mia talef', '700,000', 'سَبْعْمْيَة تَالَفْ', '', 'u'],
  ['Temenmia talef', '800,000', 'تْمَنْمْيَة تَالَفْ', '', 'u'],
  ['Ts3mia talef', '900,000', 'تَسْعْمْيَة تَالَفْ', '', 'u'],
  ['Mlyoun', '1,000,000', 'مْلْيُونْ'],
  ['Zouj mlayen', '2,000,000', 'زُوجْ مْلَايَنْ'],
  ['Tlet mlayen', '3,000,000', 'تْلَتْ مْلَايَنْ'],
  ['Reb3 mlayen', '4,000,000', 'رْبَعْ مْلَايَنْ'],
  ['Khems mlayen', '5,000,000', 'خْمَسْ مْلَايَنْ'],
  ['Sett mlayen', '6,000,000', 'سْتّْ مْلَايَنْ'],
  ['Seb3 mlayen', '7,000,000', 'سْبَعْ مْلَايَنْ'],
  ['Tmenia mlayen', '8,000,000', 'تْمَنْيَة مْلَايَنْ'],
  ['Tes3 mlayen', '9,000,000', 'تْسَعْ مْلَايَنْ'],
  ['Hdach melyoun', '11,000,000', 'حْدَاشْ مَلْيُونْ'],
  ['3echrin melyoun', '20,000,000', 'عَشْرِينْ مَلْيُونْ'],
  ['Khamsin melyoun', '50,000,000', 'خَمْسِينْ مَلْيُونْ'],
]},
{id:'time', name:'Time', week:5, deck:'Telling the Time', items:[
  ['Ch7al rahi sa3a?', 'What time is it?', 'شْحَالْ رَاهِي السَّاعَة؟'],
  ['Rahi [hour]', 'It is [hour] o’clock', 'رَاهِي'],
  ['Sa3a', 'hour', 'سَاعَة'],
  ['Swaye3', 'hours', 'سْوَايَعْ'],
  ['D9i9a', 'minute', 'دْقِيقَة'],
  ['D9aye9', 'minutes', 'دْقَايَقْ'],
  ['Nos', 'half · half past', 'نُصّْ', 'Nes'],
  ['Rbe3', 'quarter · quarter past', 'رْبَعْ', 'Rba3'],
  ['Ghir · 9al', 'minus · less · to the hour', 'غِيرْ', '', 'u'],
  ['ta3 sba7', 'in the morning · am', 'تَاعْ الصّْبَاحْ', '', 'u'],
  ['ta3 3chiya', 'in the afternoon · pm', 'تَاعْ الْعْشِيَّة', '', 'u'],
  ['ta3 lil', 'at night', 'تَاعْ اللِّيلْ', '', 'u']
]},
{id:'money', name:'Money', week:6, deck:'Currency', items:[
  ['Khemsemia · Mia doro', '5 DA', 'خَمْسْمْيَة', '', 'u'],
  ['Alfrak', '10 DA', 'أَلْفْرَنْكْ', '', 'u'],
  ['Alfin', '20 DA', 'أَلْفِينْ'],
  ['Teltalaf', '30 DA', 'تَلْتْ الَافْ'],
  ['Reb3alaf', '40 DA', 'رَبْعْ الَافْ'],
  ['Khemsalaf', '50 DA', 'خَمْسْ الَافْ'],
  ['Settalaf', '60 DA', 'سَتّْ الَافْ'],
  ['Seb3alaf', '70 DA', 'سَبْعْ الَافْ'],
  ['Tmenalaf', '80 DA', 'تْمَنْ الَافْ'],
  ['Tes3alaf', '90 DA', 'تَسْعْ الَافْ'],
  ['3chralaf', '100 DA', 'عَشْرْ الَافْ'],
  ['3chrinalef', '200 DA', 'عَشْرِينْ أَلَفْ'],
  ['Tlatinalef', '300 DA', 'تْلَاتِينْ أَلَفْ'],
  ['Rb3inalef', '400 DA', 'رَبْعِينْ أَلَفْ'],
  ['Khemsinalef', '500 DA', 'خَمْسِينْ أَلَفْ'],
  ['Settinalef', '600 DA', 'سِتِّينْ أَلَفْ'],
  ['Seb3inalef', '700 DA', 'سَبْعِينْ أَلَفْ'],
  ['Tmaninalef', '800 DA', 'تْمَانِينْ أَلَفْ'],
  ['Ts3inalef', '900 DA', 'تَسْعِينْ أَلَفْ'],
  ['Wahed w 3achrinalef', '210 DA', 'وَاحَدْ وْ عَشْرِينْ أَلَفْ'],
  ['Tnin w 3chrinalef', '220 DA', 'تْنِينْ وْ عَشْرِينْ أَلَفْ'],
  ['Tlata w 3chrinalef', '230 DA', 'تْلَاتَة وْ عَشْرِينْ أَلَفْ'],
  ['Reb3a w 3chrinalef', '240 DA', 'رَبْعَة وْ عَشْرِينْ أَلَفْ'],
  ['Khemsa w 3chrinalef', '250 DA', 'خَمْسَة وْ عَشْرِينْ أَلَفْ'],
  ['Setta w 3chrinalef', '260 DA', 'سِتَّة وْ عَشْرِينْ أَلَفْ'],
  ['Seb3a w 3chrinalef', '270 DA', 'سَبْعَة وْ عَشْرِينْ أَلَفْ'],
  ['Tmenia w 3chrinalef', '280 DA', 'تْمَنْيَة وْ عَشْرِينْ أَلَفْ'],
  ['Tes3a w 3chrinalef', '290 DA', 'تَسْعَة وْ عَشْرِينْ أَلَفْ'],
  ['Miatalef', '1,000 DA', 'مْيَة تَالَفْ'],
  ['Mitinalef', '2,000 DA', 'مْيَتِينْ أَلَفْ'],
  ['Teltemiatalef', '3,000 DA', 'تَلْتْمْيَة تَالَفْ', '', 'u'],
  ['Reb3emiatalef', '4,000 DA', 'رَبْعْمْيَة تَالَفْ', '', 'u'],
  ['Khemsemiatalef', '5,000 DA', 'خَمْسْمْيَة تَالَفْ', '', 'u'],
  ['Settemiatalef', '6,000 DA', 'سَتّْمْيَة تَالَفْ', '', 'u'],
  ['Seb3emiatalef', '7,000 DA', 'سَبْعْمْيَة تَالَفْ', '', 'u'],
  ['Temnemiatalef', '8,000 DA', 'تْمَنْمْيَة تَالَفْ', '', 'u'],
  ['Tes3emiatalef', '9,000 DA', 'تَسْعْمْيَة تَالَفْ', '', 'u'],
  ['Melyoun', '10,000 DA', 'مَلْيُونْ'],
  ['Zouj mlayen', '20,000 DA', 'زُوجْ مْلَايَنْ'],
  ['Telt mlayen', '30,000 DA', 'تَلْتْ مْلَايَنْ'],
  ['Reb3 mlayen', '40,000 DA', 'رْبَعْ مْلَايَنْ'],
  ['Khems mlayen', '50,000 DA', 'خْمَسْ مْلَايَنْ'],
  ['Sett mlayen', '60,000 DA', 'سْتّْ مْلَايَنْ'],
  ['Seb3 mlayen', '70,000 DA', 'سْبَعْ مْلَايَنْ'],
  ['Temn mlayen', '80,000 DA', 'تْمَنْ مْلَايَنْ'],
  ['Tes3 mlayen', '90,000 DA', 'تْسَعْ مْلَايَنْ'],
  ['3chr mlayen', '100,000 DA', 'عَشْرْ مْلَايَنْ'],
  ['7dach melyoun', '110,000 DA', 'حْدَاشْ مَلْيُونْ'],
  ['Tnach melyoun', '120,000 DA', 'طْنَاشْ مَلْيُونْ']
]},
{id:'pronouns', name:'Pronouns', week:7, deck:'The Pronouns', items:[
  ['Ana', 'I', 'أَنَا'],
  ['Nta · Ntaya', 'you (m)', 'نْتَا'],
  ['Nti · Ntiya', 'you (f)', 'نْتِي'],
  ['Houwa · Howa', 'he', 'هُوَّ'],
  ['Hia · Hiya', 'she', 'هِيَّ'],
  ['7na', 'we', 'حْنَا'],
  ['Ntouma', 'you (plural)', 'نْتُومَا'],
  ['Houma', 'they', 'هُومَا'],
  ['ta3i', 'my · mine', 'تَاعِي', 'dyali'],
  ['ta3ek', 'your · yours — to one person', 'تَاعَكْ', 'dyalek'],
  ['ta3ou', 'his', 'تَاعُو', 'dyalou'],
  ['ta3ha · ta7a', 'her · hers', 'تَاعْهَا', 'dyalha'],
  ['ta3na', 'our · ours', 'تَاعْنَا', 'dyalna'],
  ['ta3koum', 'your · yours — to several people', 'تَاعْكُمْ', 'dyalkoum'],
  ['ta3houm', 'their · theirs', 'تَاعْهُمْ', 'dyalhoum'],
  ['Hada · Had', 'this (m) · this one (m)', 'هَادَا'],
  ['Hadak', 'that (m) · that one (m)', 'هَادَاكْ'],
  ['Hadi', 'this (f) · this one (f)', 'هَادِي'],
  ['Hadik', 'that (f) · that one (f)', 'هَادِيكْ'],
  ['Hadou', 'these', 'هَادُو'],
  ['Hadouk', 'those', 'هَادُوكْ']
]},
{id:'present', name:'Present verbs', week:8, deck:'The Present', items:[
  ['Yekteb', 'to write · he writes', 'يَكْتَبْ'],
  ['Yekdeb', 'to lie · he lies', 'يَكْذَبْ', '', 'u'],
  ['Y9ra', 'to read · he reads', 'يَقْرَا'],
  ['Ymchi', 'to walk · he walks', 'يَمْشِي'],
  ['Ychrab', 'to drink · he drinks', 'يَشْرَبْ']
]}
]
};

/*
  Verbs tab. persons are in the order of the conjugation slide.
  Prompt: "you write (masc)". Answer: pronoun + ra- form + verb form, e.g. "nta rak tekteb".
  base / third are the English verb ("write" / "writes") used to build the prompt.
  Each verb lists only the forms the slides give; missing persons are simply not tested.
*/
window.VOCAB.persons = [
  // [id, Darja pronoun, English label, English subject, tag after the verb, other accepted spellings]
  ['ana', 'Ana', 'I', 'I', ''], ['nta', 'Nta', 'you (m)', 'you', '(masc)', ['ntaya']], ['nti', 'Nti', 'you (f)', 'you', '(fem)', ['ntiya']],
  ['houwa', 'Houwa', 'he', 'he', '', ['howa']], ['hia', 'Hia', 'she', 'she', '', ['hiya']],
  ['7na', '7na', 'we', 'we', ''], ['ntouma', 'Ntouma', 'you (plural)', 'you', '(plural)'], ['houma', 'Houma', 'they', 'they', '']
];
// ra- goes between the pronoun and the verb: "Ntouma rakoum tektebou" (you (plural) are writing)
window.VOCAB.ra = {ana:'Rani', nta:'Rak', nti:'Raki', houwa:'Rahou', hia:'Rahi', '7na':'Rana', ntouma:'Rakoum', houma:'Rahoum'};
window.VOCAB.verbs = [
  {id:'kteb', name:'Yekteb', en:'to write', base:'write', third:'writes', deck:'The Present', forms:{ana:'Nekteb', nta:'Tekteb', nti:'Tektebi', houwa:'Yekteb', hia:'Tekteb', '7na':'Nektebou', ntouma:'Tektebou', houma:'Yektebou'}},
  {id:'9ra', name:'Y9ra', en:'to read', base:'read', third:'reads', deck:'The Present', forms:{ana:'N9ra', nta:'T9ra', nti:'T9rai', houwa:'Y9ra', hia:'T9ra', '7na':'N9raou', ntouma:'T9raou', houma:'Y9raou'}},
  {id:'mchi', name:'Ymchi', en:'to walk', base:'walk', third:'walks', deck:'The Present', forms:{ana:'Nmchi', nta:'Tmchi', nti:'Tmchi', houwa:'Ymchi', hia:'Tmchi', '7na':'Nmchiou', ntouma:'Tmchiou', houma:'Ymchiou'}},
  // gen:true = the slides list the verb but not its table, so the forms are built with the slide formula
  {id:'kdeb', name:'Yekdeb', en:'to lie', base:'lie', third:'lies', deck:'The Present', gen:true, forms:{ana:'Nekdeb', nta:'Tekdeb', nti:'Tekdebi', houwa:'Yekdeb', hia:'Tekdeb', '7na':'Nekdebou', ntouma:'Tekdebou', houma:'Yekdebou'}},
  {id:'chrab', name:'Ychrab', en:'to drink', base:'drink', third:'drinks', deck:'The Present', gen:true, forms:{ana:'Nchrab', nta:'Tchrab', nti:'Tchrabi', houwa:'Ychrab', hia:'Tchrab', '7na':'Nchrabou', ntouma:'Tchrabou', houma:'Ychrabou'}},
  {id:'skn', name:'Yeskoun', en:'to live (somewhere)', base:'live', third:'lives', deck:'Deck 1', forms:{ana:'Neskoun', nta:'Teskoun', nti:'Teskni', houwa:'Yeskoun', hia:'Teskoun'}},
  {id:'khdem', name:'Yekhdem', en:'to work', base:'work', third:'works', deck:'Deck 1', forms:{ana:'Nakhdem', nta:'Tekhdem', nti:'Tekhdemi', houwa:'Yekhdem', hia:'Tekhdem'}},
  {id:'7eb', name:'Y7eb', en:'to like', base:'like', third:'likes', deck:'Deck 1', forms:{ana:'N7eb', nta:'T7eb', nti:'T7ebbi', houwa:'Y7eb', hia:'T7eb'}}
];
