/*
  Darja Drill — vocab bank
  ------------------------------------------------------------
  One entry per item:  [darja, english, arabic, alt, flags]
    darja   Arabizi exactly as the slides write it
    english the meaning; " — " or " · " separates accepted alternatives,
            "— to a man / to a woman" marks who you're speaking to
    arabic  vowel-marked Arabic script for the voice ("" = no audio)
            Always keep the shadda (ّ) on doubled letters.
    alt     other forms heard (shown as "also heard")
    flags   "x" = not from the slides (Claude's addition)
            "u" = Arabic spelling unsure — check with the teacher

  To add a new week: copy a topic block, give it a new id, set week to the
  next number, and paste the new items in. Nothing else needs to change.
*/
window.VOCAB = {
updated: '2026-09-26',
topics: [
{id:'questions', name:'Questions', week:1, deck:'Deck 1', items:[
  ['Wech rak?', 'How are you? — to a man', 'وَاشْ رَاكْ؟', 'Ki rak? · Labas?'],
  ['Wech raki?', 'How are you? — to a woman', 'وَاشْ رَاكِي؟', 'Ki raki? · Labas?'],
  ['Labas, hamdoulleh — w nta?', 'Fine, thank God, and you? — to a man', 'لَابَاسْ، الْحَمْدُ لِلَّه، وْ نْتَا؟'],
  ['Labas, hamdoulleh — w nti?', 'Fine, thank God, and you? — to a woman', 'لَابَاسْ، الْحَمْدُ لِلَّه، وْ نْتِي؟'],
  ['Wech asmek? · Wesmek?', "What's your name?", 'وَاشْ اسْمَكْ؟', 'Ki ysemmouk?'],
  ['Asmi Ahmed', 'My name is Ahmed', 'اسْمِي أَحْمَدْ'],
  ['Men win nta?', 'Where are you from? — to a man', 'مِنْ وِينْ نْتَا؟', 'Mnin nta?'],
  ['Men win nti?', 'Where are you from? — to a woman', 'مِنْ وِينْ نْتِي؟', 'Mnin nti?'],
  ['Ana men Alger', 'I am from Algiers', 'أَنَا مِنْ الدْزَايَرْ', '', 'u'],
  ['Ch7al fi 3omrek?', 'How old are you?', 'شْحَالْ فِي عُمْرَكْ؟'],
  ['3andi 30 sna · Fi 3omri 30', 'I am 30 years old', 'عَنْدِي تْلَاتِينْ سْنَة'],
  ['Win teskoun?', 'Where do you live? — to a man', 'وِينْ تَسْكُنْ؟'],
  ['Win teskni?', 'Where do you live? — to a woman', 'وِينْ تَسْكْنِي؟'],
  ['Ana neskoun fi Alger', 'I live in Algiers', 'أَنَا نَسْكُنْ فِي الدْزَايَرْ', '', 'u'],
  ['Wech tekhdem?', 'What do you do for work? — to a man', 'وَاشْ تَخْدَمْ؟'],
  ['Wech tekhdemi?', 'What do you do for work? — to a woman', 'وَاشْ تَخْدْمِي؟'],
  ['Ana nakhdem fi [field]', 'I work in [field]', 'أَنَا نَخْدَمْ فِي'],
  ['Wach t7eb dir?', 'What do you like to do? — to a man', 'وَاشْ تْحَبّْ دِيرْ؟'],
  ['Wach t7ebbi diri?', 'What do you like to do? — to a woman', 'وَاشْ تْحَبِّي دِيرِي؟'],
  ['N7eb ndir sport w ne9ra lektouba', 'I like doing sport and reading books', 'نْحَبّْ نْدِيرْ السْبُورْ وْ نَقْرَا لَكْتُوبَة', '', 'u']
]},
{id:'endings', name:'Endings & verbs', week:1, deck:'Deck 1', items:[
  ['asmi', 'my name', 'اسْمِي'],
  ['asmek', 'your name', 'اسْمَكْ'],
  ['asmou', 'his name', 'اسْمُو'],
  ['asmha · assemha', 'her name', 'اسْمْهَا'],
  ['3omri', 'my age', 'عُمْرِي'],
  ['3omrek', 'your age', 'عُمْرَكْ'],
  ['3omrou', 'his age', 'عُمْرُو'],
  ['3omrha · 3morha', 'her age', 'عُمْرْهَا'],
  ['neskoun', 'I live', 'نَسْكُنْ'],
  ['teskoun', 'you (m) live · she lives', 'تَسْكُنْ'],
  ['teskni', 'you (f) live', 'تَسْكْنِي'],
  ['yeskoun', 'he lives', 'يَسْكُنْ'],
  ['nakhdem', 'I work', 'نَخْدَمْ'],
  ['tekhdem', 'you (m) work · she works', 'تَخْدَمْ'],
  ['tekhdemi', 'you (f) work', 'تَخْدْمِي'],
  ['yekhdem', 'he works', 'يَخْدَمْ'],
  ['n7eb', 'I like', 'نْحَبّْ'],
  ['t7eb', 'you (m) like · she likes', 'تْحَبّْ'],
  ['t7ebbi', 'you (f) like', 'تْحَبِّي'],
  ['y7eb', 'he likes', 'يْحَبّْ']
]},
{id:'stems', name:'Him & her', week:1, deck:'Deck 1', items:[
  ['Fi 3omrou [n]', 'He is [n] years old', 'فِي عُمْرُو'],
  ['Fi 3morha [n]', 'She is [n] years old', 'فِي عُمْرْهَا'],
  ['Yeskoun fi [place]', 'He lives in [place]', 'يَسْكُنْ فِي'],
  ['Teskoun fi [place]', 'She lives in [place]', 'تَسْكُنْ فِي'],
  ['Yekhdem fi [place]', 'He works in [place]', 'يَخْدَمْ فِي'],
  ['Tekhdem fi [place]', 'She works in [place]', 'تَخْدَمْ فِي'],
  ['N7eb ndir [activity]', 'I like doing [activity]', 'نْحَبّْ نْدِيرْ'],
  ['Houwa men [place]', 'He is from [place]', 'هُوَّ مِنْ', '', 'x'],
  ['Hiya men [place]', 'She is from [place]', 'هِيَّ مِنْ', '', 'x'],
  ['Men win houwa?', 'Where is he from?', 'مِنْ وِينْ هُوَّ؟', '', 'x'],
  ['Men win hiya?', 'Where is she from?', 'مِنْ وِينْ هِيَّ؟', '', 'x']
]},
{id:'family', name:'Family', week:1, deck:'Deck 1', items:[
  ['Baba · Bouya', 'my father', 'بَابَا'],
  ['Yemma · Mama', 'my mother', 'يَمَّا'],
  ['Khouya', 'my brother', 'خُويَا'],
  ['Khti', 'my sister', 'خْتِي'],
  ['Weldi · Wlidi · Bni', 'my son', 'وَلْدِي'],
  ['Benti', 'my daughter', 'بَنْتِي'],
  ['Jedi', 'my grandfather', 'جَدِّي'],
  ['Jedati · Mani · Mima · 7ana', 'my grandmother', 'جَدَّتِي'],
  ['3emi', 'my paternal uncle — father’s brother', 'عَمِّي'],
  ['3emti', 'my paternal aunt — father’s sister', 'عَمّْتِي'],
  ['Khali', 'my maternal uncle — mother’s brother', 'خَالِي'],
  ['Khalti', 'my maternal aunt — mother’s sister', 'خَالْتِي'],
  ['Weld 3emi', 'my cousin, son of my father’s brother', 'وَلْدْ عَمِّي'],
  ['Weld 3emti', 'my cousin, son of my father’s sister', 'وَلْدْ عَمّْتِي'],
  ['Weld khali', 'my cousin, son of my mother’s brother', 'وَلْدْ خَالِي'],
  ['Weld khalti', 'my cousin, son of my mother’s sister', 'وَلْدْ خَالْتِي'],
  ['Bent 3emi', 'my cousin, daughter of my father’s brother', 'بَنْتْ عَمِّي'],
  ['Bent 3emti', 'my cousin, daughter of my father’s sister', 'بَنْتْ عَمّْتِي'],
  ['Bent khali', 'my cousin, daughter of my mother’s brother', 'بَنْتْ خَالِي'],
  ['Bent khalti', 'my cousin, daughter of my mother’s sister', 'بَنْتْ خَالْتِي'],
  ['Weld khouya', 'my nephew — my brother’s son', 'وَلْدْ خُويَا'],
  ['Weld khti', 'my nephew — my sister’s son', 'وَلْدْ خْتِي'],
  ['Bent khouya', 'my niece — my brother’s daughter', 'بَنْتْ خُويَا'],
  ['Bent khti', 'my niece — my sister’s daughter', 'بَنْتْ خْتِي']
]},
{id:'phrases', name:'Phrases', week:1, deck:'Deck 1', items:[
  ['Ana dziri', 'I am Algerian — a man', 'أَنَا دْزِيرِي'],
  ['Ana dziriya', 'I am Algerian — a woman', 'أَنَا دْزِيرِيَّة'],
  ['Ana wahrani', 'I am from Oran — a man', 'أَنَا وَهْرَانِي'],
  ['Ana wahraniya', 'I am from Oran — a woman', 'أَنَا وَهْرَانِيَّة'],
  ['Labas', 'fine', 'لَابَاسْ'],
  ['Ghaya', 'great', 'غَايَة'],
  ['Hamdoulleh', 'thank God', 'الْحَمْدُ لِلَّه']
]},
{id:'calendar', name:'Calendar', week:3, deck:'Deck 3', items:[
  ['L7ad', 'Sunday', 'لْحَدْ'],
  ['Tnin', 'Monday', 'لَتْنِينْ'],
  ['Tleta', 'Tuesday', 'تْلَاتَة'],
  ['Lareb3a', 'Wednesday', 'لَارْبْعَة'],
  ['Lkhmis', 'Thursday', 'لَخْمِيسْ'],
  ['Djem3a', 'Friday', 'الْجَمْعَة'],
  ['Sebt', 'Saturday', 'السَّبْتْ'],
  ['Lbare7', 'yesterday', 'الْبَارَحْ'],
  ['Ghedwa', 'tomorrow', 'غُدْوَة'],
  ['Loul bara7', 'the day before yesterday', 'لُولْ الْبَارَحْ'],
  ['Ghir ghedwa', 'the day after tomorrow', 'غِيرْ غُدْوَة'],
  ['Youm', 'day', 'يُومْ'],
  ['Nhar', 'daytime — a calendar day', 'نْهَارْ'],
  ['Smana', 'week', 'سْمَانَة'],
  ['Chhar', 'month', 'شْهَرْ'],
  ['3am', 'year', 'عَامْ'],
  ['Fousoul', 'the seasons', 'الْفُصُولْ'],
  ['Rbi3', 'spring', 'الرّْبِيعْ'],
  ['Sif', 'summer', 'الصِّيفْ'],
  ['Khrif', 'autumn', 'الْخْرِيفْ'],
  ['Chta', 'winter', 'الشّْتَا'],
  ['Janvi · Janvier', 'January', 'جَانْفِي'],
  ['Fervryi · Février', 'February', 'فِيفْرِي'],
  ['Mars', 'March', 'مَارْسْ'],
  ['Avril', 'April', 'أَفْرِيلْ'],
  ['Mai', 'May', 'مَايْ'],
  ['Juin', 'June', 'جْوَانْ'],
  ['Juillet', 'July', 'جْوِيلِيَّة'],
  ['Aout', 'August', 'أُوتْ'],
  ['Septembre', 'September', 'سَبْتَمْبَرْ'],
  ['Octobre', 'October', 'أُكْتُوبَرْ'],
  ['Novembre', 'November', 'نُوفَمْبَرْ'],
  ['Decembre', 'December', 'دِيسَمْبَرْ'],
  ['Smana ljaya', 'next week', 'السّْمَانَة الْجَايَّة'],
  ['Smana li fatat', 'last week', 'السّْمَانَة اللِّي فَاتَتْ'],
  ['Chhar ljay', 'next month', 'الشّْهَرْ الْجَايْ'],
  ['Chhar li fat', 'last month', 'الشّْهَرْ اللِّي فَاتْ'],
  ['L3am ljay', 'next year', 'الْعَامْ الْجَايْ'],
  ['L3am li fat', 'last year', 'الْعَامْ اللِّي فَاتْ'],
  ['Ghedwa Ljam3a', 'tomorrow is Friday', 'غُدْوَة الْجَمْعَة'],
  ['Lbare7 sebt', 'yesterday was Saturday', 'الْبَارَحْ السَّبْتْ'],
  ['Ghir ghedwa l7ad', 'the day after tomorrow is Sunday', 'غِيرْ غُدْوَة لْحَدْ'],
  ['Loul bare7 kouna lkhmis', 'the day before yesterday was Thursday', 'لُولْ الْبَارَحْ كُنَّا لَخْمِيسْ'],
  ['Netla9aw nhar lerb3a', 'we will see each other on Wednesday', 'نْتْلَاقَاوْ نْهَارْ لَارْبْعَة'],
  ['Samana li fatet kount m3a mama', 'last week I was with my mum', 'السّْمَانَة اللِّي فَاتَتْ كُنْتْ مْعَا مَامَا'],
  ['L3otla ray7a tkoun chhar ljay', 'the holiday will be next month', 'الْعُطْلَة رَايْحَة تْكُونْ الشّْهَرْ الْجَايْ'],
  ['L3am ljay nro7 nsafer', 'next year I will go travelling', 'الْعَامْ الْجَايْ نْرُوحْ نْسَافَرْ']
]},
{id:'numbers', name:'Numbers', week:4, deck:'Numbers 1–2', items:[
  ['Sifr', '0', 'صِفْرْ'],
  ['Wa7ad', '1', 'وَاحَدْ'],
  ['Zouj · Tnin', '2', 'زُوجْ'],
  ['Tletta', '3', 'تْلَاتَة'],
  ['Rab3a', '4', 'رَبْعَة'],
  ['Khemsa', '5', 'خَمْسَة'],
  ['Setta', '6', 'سِتَّة'],
  ['Sab3a', '7', 'سَبْعَة'],
  ['Tménya', '8', 'تْمَنْيَة'],
  ['Tas3a', '9', 'تَسْعَة'],
  ['3achra', '10', 'عَشْرَة'],
  ['7dash', '11', 'حْدَاشْ'],
  ['Tnash', '12', 'طْنَاشْ'],
  ['Tlettash', '13', 'تْلَطَّاشْ'],
  ['Rbe3ttash', '14', 'رْبَعْطَاشْ'],
  ['Khmsttash', '15', 'خْمَسْطَاشْ'],
  ['Settash', '16', 'سَطَّاشْ'],
  ['Sba3ttash', '17', 'سْبَعْطَاشْ'],
  ['Tmenttash', '18', 'تْمَنْطَاشْ'],
  ['Tse3ttash', '19', 'تْسَعْطَاشْ'],
  ['3achrin', '20', 'عَشْرِينْ'],
  ['Tlatin', '30', 'تْلَاتِينْ'],
  ['Rab3in', '40', 'رَبْعِينْ'],
  ['Khamsin', '50', 'خَمْسِينْ'],
  ['Settin', '60', 'سِتِّينْ'],
  ['Sab3in', '70', 'سَبْعِينْ'],
  ['Tmanin', '80', 'تْمَانِينْ'],
  ['Tas3in', '90', 'تَسْعِينْ'],
  ['Mia', '100', 'مْيَة'],
  ['Mitin', '200', 'مْيَتِينْ'],
  ['Teltmia', '300', 'تَلْتْمْيَة', '', 'u'],
  ['Reb3mia', '400', 'رَبْعْمْيَة', '', 'u'],
  ['Khemsmia', '500', 'خَمْسْمْيَة', '', 'u'],
  ['Settmia', '600', 'سَتّْمْيَة', '', 'u'],
  ['Seb3mia', '700', 'سَبْعْمْيَة', '', 'u'],
  ['Temnemia', '800', 'تْمَنْمْيَة', '', 'u'],
  ['Tes3mia', '900', 'تَسْعْمْيَة', '', 'u'],
  ['Alf', '1,000', 'أَلْفْ'],
  ['Alfyn', '2,000', 'أَلْفِينْ'],
  ['Teltalaf', '3,000', 'تَلْتْ الَافْ'],
  ['Reb3alaf', '4,000', 'رَبْعْ الَافْ'],
  ['Khmsalaf', '5,000', 'خَمْسْ الَافْ'],
  ['Settalaf', '6,000', 'سَتّْ الَافْ'],
  ['Seb3alaf', '7,000', 'سَبْعْ الَافْ'],
  ['Temnalaf', '8,000', 'تْمَنْ الَافْ'],
  ['Tes3alaf', '9,000', 'تَسْعْ الَافْ'],
  ['3chralaf', '10,000', 'عَشْرْ الَافْ'],
  ['7dach nalef', '11,000', 'حْدَاشْ نَالَفْ'],
  ['Tnach nalef', '12,000', 'طْنَاشْ نَالَفْ'],
  ['Tletach nalef', '13,000', 'تْلَطَّاشْ نَالَفْ'],
  ['Reb3tach nalef', '14,000', 'رْبَعْطَاشْ نَالَفْ'],
  ['Khmstach nalef', '15,000', 'خْمَسْطَاشْ نَالَفْ'],
  ['Settach nalef', '16,000', 'سَطَّاشْ نَالَفْ'],
  ['Sb3tach nalef', '17,000', 'سْبَعْطَاشْ نَالَفْ'],
  ['Tementach nalef', '18,000', 'تْمَنْطَاشْ نَالَفْ'],
  ['Ts3tach nalef', '19,000', 'تْسَعْطَاشْ نَالَفْ'],
  ['3echrin alef', '20,000', 'عَشْرِينْ أَلَفْ'],
  ['Tletin alef', '30,000', 'تْلَاتِينْ أَلَفْ'],
  ['Rb3in alef', '40,000', 'رَبْعِينْ أَلَفْ'],
  ['Khamsin alef', '50,000', 'خَمْسِينْ أَلَفْ'],
  ['Settin alef', '60,000', 'سِتِّينْ أَلَفْ'],
  ['Sb3in alef', '70,000', 'سَبْعِينْ أَلَفْ'],
  ['Tmanin alef', '80,000', 'تْمَانِينْ أَلَفْ'],
  ['Ts3in alef', '90,000', 'تَسْعِينْ أَلَفْ'],
  ['Mia talef', '100,000', 'مْيَة تَالَفْ'],
  ['Mitin alef', '200,000', 'مْيَتِينْ أَلَفْ'],
  ['Tletemia talef', '300,000', 'تَلْتْمْيَة تَالَفْ', '', 'u'],
  ['Reb3emia talef', '400,000', 'رَبْعْمْيَة تَالَفْ', '', 'u'],
  ['Khmsmia talef', '500,000', 'خَمْسْمْيَة تَالَفْ', '', 'u'],
  ['Settmia talef', '600,000', 'سَتّْمْيَة تَالَفْ', '', 'u'],
  ['Sb3mia talef', '700,000', 'سَبْعْمْيَة تَالَفْ', '', 'u'],
  ['Temenmia talef', '800,000', 'تْمَنْمْيَة تَالَفْ', '', 'u'],
  ['Ts3mia talef', '900,000', 'تَسْعْمْيَة تَالَفْ', '', 'u'],
  ['Mlyoun', '1,000,000', 'مْلْيُونْ'],
  ['Zouj mlayen', '2,000,000', 'زُوجْ مْلَايَنْ'],
  ['Tlet mlayen', '3,000,000', 'تْلَتْ مْلَايَنْ'],
  ['Reb3 mlayen', '4,000,000', 'رْبَعْ مْلَايَنْ'],
  ['Khems mlayen', '5,000,000', 'خْمَسْ مْلَايَنْ'],
  ['Sett mlayen', '6,000,000', 'سْتّْ مْلَايَنْ'],
  ['Seb3 mlayen', '7,000,000', 'سْبَعْ مْلَايَنْ'],
  ['Tmenia mlayen', '8,000,000', 'تْمَنْيَة مْلَايَنْ'],
  ['Tes3 mlayen', '9,000,000', 'تْسَعْ مْلَايَنْ'],
  ['Hdach melyoun', '11,000,000', 'حْدَاشْ مَلْيُونْ'],
  ['3echrin melyoun', '20,000,000', 'عَشْرِينْ مَلْيُونْ'],
  ['Khamsin melyoun', '50,000,000', 'خَمْسِينْ مَلْيُونْ'],
]}
]
};
